install:
  # install gcc-4.8 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.7
language: bash
script:
  - cd phasing_family/src/ && make && ./test_phaser && cd ../../ && ./run_utest.sh
